image:
  - "Visual Studio 2019"

branches:
  only:
    - master
    - develop
    - /^v\d.*$/
    - /^deploy-test(-.*)?$/

# Add this to enable and trigger RDP
init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: if($blockRdp) { iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/break-rdp.ps1')) }

build: off

configuration:
  - Release

for:
  - matrix:
      only:
        - image: "Visual Studio 2019"

    install:
      - git submodule update --init --recursive

    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
      - C:\msys64\usr\bin\bash -lc "cd \"%APPVEYOR_BUILD_FOLDER%\" && scripts/appveyor-win.sh"

    # For debugging, you can also add the file listing here again
    after_build:
      - echo "--- START FILE LISTING ---"
      - ps: Get-ChildItem -Path "." -Recurse -ErrorAction SilentlyContinue
      - echo "--- END FILE LISTING ---"

    artifacts:
      - path: Chiaki
        name: Chiaki
      - path: Chiaki-PDB
        name: Chiaki-PDB