image:
  - "Visual Studio 2019"

branches:
  only:
    - master
    - develop
    - /^v\d.*$/
    - /^deploy-test(-.*)?$/

configuration:
  - Release

environment:
  PYTHON: "C:\\Python37"

install:
  - ls c/qt
  # - git submodule update --init --recursive
  # - choco install python --version 3.7.9 -y
  # - SET PATH=C:\Python37;C:\Python37\Scripts;%PATH%

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - C:\msys64\usr\bin\bash -lc "cd \"%APPVEYOR_BUILD_FOLDER%\" && scripts/appveyor-win.sh"

artifacts:
  - path: Chiaki
    name: Chiaki
  - path: Chiaki-PDB
    name: Chiaki-PDB
